config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'application#home'

  resources :members
  resources :projects do
    get 'create-in-hb', action: 'create_in_hb', on: :member
    get 'azure-hooks-create', action: 'azure_hooks_create', on: :member
  end
  resources :tasks

  resources :organizations do
    get 'edit_hubstaff_access', to: 'organizations#edit_hubstaff_access', on: :member
    get '/hubstaff_start_auth_code_callback', to: 'organizations#hubstaff_start_auth_code', on: :collection
    post 'update_hubstaff_start_auth_code', to: 'organizations#update_hubstaff_start_auth_code', on: :member

    resources :members do
      get 'get-from-azure', to: 'members#azure_list', on: :collection
    end

    resources :projects do
      get 'get-from-azure', to: 'projects#azure_list', on: :collection
    end
  end

  scope :api do
    root to: 'api/base#home'

    scope :tasks do
      post 'azure_hook_create', to: 'api/tasks#azure_hook_create', as: :azure_hook_task_create
      post 'azure_hook_update', to: 'api/tasks#azure_hook_update', as: :azure_hook_task_update
      post 'azure_hook_destroy', to: 'api/tasks#azure_hook_destroy', as: :azure_hook_task_destroy
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  include Rails.application.routes.url_helpers
  include Connectable

  belongs_to :organization
  has_many :tasks, dependent: :destroy
  has_many :activities
  after_create :after_create_actions

  def title
    azure_name
  end

  def tracked
    activities.sum(:tracked)
  end

  def tracked_hours
    (tracked/3600.0).ceil(2)
  end

  def create_project_in_hubstaff
    members = organization.members.select {|mem| mem.hubstaff_id.present? }.map {|mem| { 'user_id' => mem.hubstaff_id.to_i, 'role' => 'user' }}

    res = HubstaffClient.new.organization_project_create organization.fresh_hubstaff_access_token, organization.hubstaff_id, azure_name, members
    self.hubstaff_id = res.parsed_response['project']['id']
    self.created_in_hubstaff = true
    self.save

    Rails.cache.clear
    true
  rescue => e
    Rails.logger.error e
  end

  def azure_hooks_create
    access_token = Rails.application.credentials[Rails.env.to_sym][:api_access_token]
    azure_hook_create 'workitem.created', azure_hook_task_create_url(token: access_token)
    azure_hook_create 'workitem.updated', azure_hook_task_update_url(token: access_token)
    azure_hook_create 'workitem.deleted', azure_hook_task_destroy_url(token: access_token)
    update_attribute :azure_hooks_created, true
    true
  rescue => e
    Rails.logger.error e
  end

  def azure_hook_create event_type, callback_url
    AzureClient.new.project_subscription_create(
      organization.azure_id,
      azure_id,
      event_type,
      callback_url,
      organization.azure_access_token
    )
  end

  private

  def after_create_actions
    azure_hooks_create if organization.auto_create_azure_hooks_on_project_create?
    create_project_in_hubstaff if organization.auto_create_hubstaff_project_on_project_create?
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: %i(create_in_hb azure_hooks_create show edit update)

  def index
    @projects = Project.all
  end

  def azure_list
    @organization = Organization.find(params[:organization_id])

    res = AzureClient.new.projects @organization.azure_id, @organization.azure_access_token

    res.parsed_response['value'].each do |raw_project|
      next if Project.where(azure_id: raw_project['id']).any?

      project = Project.new
      project.azure_id = raw_project['id']
      project.azure_name = raw_project['name']
      project.organization = @organization
      project.save
    end

    redirect_to organization_path @organization
  end

  def azure_hooks_create
    @project.azure_hooks_create
  rescue => e
    Rails.logger.error e
  ensure
    redirect_back(fallback_location: project_path(@project))
  end

  def create_in_hb
    @project.create_project_in_hubstaff
  rescue => e
    Rails.logger.error e
  ensure
    redirect_back(fallback_location: project_path(@project))
  end

  def edit
    @hubstaff_projects = @project.organization.hubstaff_projects
  end

  def update
    if @project.update_attributes project_params
      redirect_to project_path @project
    else
      render :edit
    end
  end

  private

  def find_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:hubstaff_id)
  end
end

app/views/projects/edit.html.erb
<div class="resource_title">
  <span>Project <%= @project.id %></span>
  <h1><%= @project.title %></h1>
</div>

<%= simple_form_for @project do |f| %>
  <%= f.input :azure_id, readonly: true %>
  <%= f.input :azure_name, readonly: true %>
  <%= f.input :hubstaff_id, as: :select, collection: @hubstaff_projects.map {|raw| [raw['name'], raw['id']]} %>
  <%= f.button :submit, class: 'btn primary' %>
<% end %>

app/views/projects/index.html.erb
<h1>Проекты</h1>

<table>
  <thead>
    <tr>
      <td></td>
      <td>Организиция</td>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td class='main'><%= link_to project.title, project_path(project) %></td>
        <td><%= link_to project.organization.title, organization_path(project.organization) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/show.html.erb
<div class="resource_title">
  <span>Проект <%= @project.id %></span>
  <h1>
    <%= @project.title %>
    <%= render partial: 'connectable/statuses', locals: { resourse: @project } %>
  </h1>
</div>

<div class="extend_info">
  <p>azure_id: <%= @project.azure_id %></p>
  <p>Название в azure: <%= @project.azure_name %></p>

  <% if @project.azure_hooks_created? %>
    <p><%= link_to 'Хуки в azure созданы', 'javascript:void(0)', class: 'btn success small' %></p>
  <% else %>
    <p><%= link_to 'Создать хуки в azure', azure_hooks_create_project_path(@project), class: 'btn primary small' %></p>
  <% end %>

  <p>hubstaff_id: <%= @project.hubstaff_id %></p>

  <% if @project.created_in_hubstaff? %>
    <p><%= link_to 'Проект в Hubstaff создан', 'javascript:void(0)', class: 'btn success small' %></p>
  <% else %>
    <p><%= link_to 'Создать проект в Hubstaff', create_in_hb_project_path(@project), class: 'btn primary small' %></p>
  <% end %>

  <p>Выполнено: <%= @project.tracked_hours %>ч</p>
</div>

<div>
  <%= link_to 'Редактировать', edit_project_path(@project), class: 'btn primary' %>
</div>

<hr />

<div>
  <span>В организации: </span>
  <%= link_to @project.organization.title, organization_path(@project.organization) %>
</div>

<hr />

<div>
  <span>Задачи:</span>

  <table>
    <tbody>
      <% @project.tasks.each do |task| %>
        <tr>
          <td class='main'><%= link_to task.title, task_path(task) %></td>
          <td><%= task.tracked_hours %>ч</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>