config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'application#home'

  resources :members
  resources :projects do
    get 'create-in-hb', action: 'create_in_hb', on: :member
    get 'azure-hooks-create', action: 'azure_hooks_create', on: :member
  end
  resources :tasks

  resources :organizations do
    get 'edit_hubstaff_access', to: 'organizations#edit_hubstaff_access', on: :member
    get '/hubstaff_start_auth_code_callback', to: 'organizations#hubstaff_start_auth_code', on: :collection
    post 'update_hubstaff_start_auth_code', to: 'organizations#update_hubstaff_start_auth_code', on: :member

    resources :members do
      get 'get-from-azure', to: 'members#azure_list', on: :collection
    end

    resources :projects do
      get 'get-from-azure', to: 'projects#azure_list', on: :collection
    end
  end

  scope :api do
    root to: 'api/base#home'

    scope :tasks do
      post 'azure_hook_create', to: 'api/tasks#azure_hook_create', as: :azure_hook_task_create
      post 'azure_hook_update', to: 'api/tasks#azure_hook_update', as: :azure_hook_task_update
      post 'azure_hook_destroy', to: 'api/tasks#azure_hook_destroy', as: :azure_hook_task_destroy
    end
  end
end

app/models/organization.rb
class Organization < ApplicationRecord
  include Connectable

  has_and_belongs_to_many :members
  has_many :projects, dependent: :destroy
  validates_presence_of :azure_id

  def title
    azure_id
  end

  # ! use this method instead hubstaff_access_token in HubstaffClient requests
  def fresh_hubstaff_access_token
    raise 'Organiaztion not connected to HB. Please edit hubstaff start auth code.' if hubstaff_token_will_end.blank?

    # still fresh
    return hubstaff_access_token if hubstaff_token_will_end - 2.hours > DateTime.now

    res = HubstaffClient.new.refresh_access_token_request hubstaff_refresh_token

    raise StandardError, res.parsed_response['error'] if res.code != 200

    self.hubstaff_access_token = res.parsed_response['access_token']
    self.hubstaff_refresh_token = res.parsed_response['refresh_token']
    self.hubstaff_token_get_at = DateTime.now
    self.hubstaff_token_will_end = DateTime.now + (res.parsed_response['expires_in'].to_i / 60.0 / 60.0).round.hours

    self.save

    hubstaff_access_token
  end

  def hubstaff_projects
    Rails.cache.fetch("organizations/#{id}/hubstaff_projects", expires_in: 1.minute) do
      res = HubstaffClient.new.organization_projects fresh_hubstaff_access_token, hubstaff_id
      res.parsed_response['projects']
    end
  end

  def self.hubstaff_users
    Rails.cache.fetch('hubstaff_users', expires_in: 2.hours) do
      raw_users = []

      Organization.all.each do |organization|
        res = HubstaffClient.new.organization_members organization.fresh_hubstaff_access_token, organization.hubstaff_id
        user_ids = res.parsed_response['members'].pluck('user_id')

        users = user_ids.map do |user_id|
          res = HubstaffClient.new.organization_user organization.fresh_hubstaff_access_token, user_id
          parsed = res.parsed_response['user']
          {
            'id' => parsed['id'],
            'name' => "#{parsed['name']} <#{parsed['email']}>"
          }
        end

        raw_users << users
      end

      raw_users.flatten.uniq
    end
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :find_organization, only: %i(show edit update destroy edit_hubstaff_access update_hubstaff_start_auth_code)
  skip_before_action :authenticate_user!, only: %i(hubstaff_start_auth_code)

  def index
    @organizations = Organization.all
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new organization_params
    if @organization.save
      redirect_to organization_path @organization
    else
      render :new
    end
  end

  def update
    if @organization.update_attributes organization_params
      redirect_to organization_path @organization
    else
      render :edit
    end
  end

  def update_hubstaff_start_auth_code
    if @organization.update_attributes organization_exparams

      res = HubstaffClient.new.access_token_request @organization.hubstaff_start_auth_code

      raise StandardError, res.parsed_response['error'] if res.code != 200

      @organization.hubstaff_access_token = res.parsed_response['access_token']
      @organization.hubstaff_refresh_token = res.parsed_response['refresh_token']
      @organization.hubstaff_token_get_at = DateTime.now
      @organization.hubstaff_token_will_end = DateTime.now + (res.parsed_response['expires_in'].to_i / 60.0 / 60.0).round.hours
      @organization.save!

      redirect_to organization_path @organization
    else
      render :edit_hubstaff_access
    end
  rescue => e
    Rails.logger.error e

    render :edit_hubstaff_access
  end

  def destroy
    @organization.destroy
    redirect_to organizations_path
  end

  private

  def find_organization
    @organization = Organization.find(params[:id])
  end

  def organization_params
    params.require(:organization).permit(:azure_id, :azure_access_token, :hubstaff_id, :auto_create_hubstaff_project_on_project_create, :auto_create_azure_hooks_on_project_create)
  end

  def organization_exparams
    params.require(:organization).permit(:hubstaff_start_auth_code)
  end
end

app/views/organizations/edit.html.erb
<div class="resource_title">
  <span>Организация <%= @organization.id %></span>
  <h1><%= @organization.title %></h1>
</div>

<%= simple_form_for @organization do |f| %>
  <%= f.input :azure_id %>
  <%= f.input :azure_access_token %>
  <%= f.input :hubstaff_id %>
  <%= f.input :auto_create_azure_hooks_on_project_create %>
  <%= f.input :auto_create_hubstaff_project_on_project_create %>
  <%= f.button :submit, class: 'btn primary' %>
<% end %>

app/views/organizations/edit_hubstaff_access.html.erb
<div class="resource_title">
  <span>Организация <%= @organization.id %></span>
  <h1><%= @organization.title %></h1>
</div>

<%= link_to 'Получить код', HubstaffClient.new.start_auth_code_url, target: 'blank' %>

<%= simple_form_for(@organization, url: update_hubstaff_start_auth_code_organization_path(@organization), method: :post) do |f| %>
  <%= f.input :hubstaff_start_auth_code, input_html: { style: 'width:100%', value: '' } %>
  <%= f.button :submit, class: 'btn primary' %>
<% end %>

app/views/organizations/hubstaff_start_auth_code.html.erb
<p>Скопируйте этот код и вставьте в поле Стартовый код доступа Hubstaff</p>
<input type="text" style="width:100%" readonly value="<%= params[:code] %>" />

app/views/organizations/index.html.erb
<h1>Организации</h1>

<table>
  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td class='main'><%= link_to organization.title, organization_path(organization) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Добавить', new_organization_path, class: 'btn primary' %>

app/views/organizations/new.html.erb
<div class="resource_title">
  <span>Организация</span>
  <h1>Новая</h1>
</div>

<%= simple_form_for @organization do |f| %>
  <%= f.input :azure_id %>
  <%= f.input :azure_access_token %>
  <%= f.input :hubstaff_id %>
  <%= f.input :auto_create_azure_hooks_on_project_create %>
  <%= f.input :auto_create_hubstaff_project_on_project_create %>
  <%= f.button :submit, class: 'btn primary' %>
<% end %>

app/views/organizations/show.html.erb
<div class="resource_title">
  <span>Организация <%= @organization.id %></span>
  <h1>
    <%= @organization.title %>
    <%= render partial: 'connectable/statuses', locals: { resourse: @organization } %>
  </h1>
</div>


<div class="extend_info">
  <p>azure_id: <%= @organization.azure_id %></p>
  <p>
    hubstaff_id: <%= @organization.hubstaff_id %>
    <%= link_to 'Настроить доступ Hubstaff', edit_hubstaff_access_organization_path(@organization) %>
  </p>
</div>


<div>
  <%= link_to 'Редактировать', edit_organization_path(@organization), class: 'btn primary' %>
  <%= link_to 'Удалить', organization_path(@organization), method: :delete, class: 'btn warn small', data: { confirm: 'Ю арэ шурэ?' }  %></p>
</div>

<hr />

<span>Сотрудники: </span>

<table>
  <tbody>
    <% @organization.members.each do |member| %>
      <tr>
        <td class='main'><%= link_to member.name, member_path(member) %></td>
        <td><%= render partial: 'connectable/statuses', locals: { resourse: member } %></td>
        <td><%= link_to 'Редактировать', edit_member_path(member) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Обновить', get_from_azure_organization_members_path(@organization), class: 'btn primary' %>

<hr />

<span>Проекты: </span>

<table>
  <tbody>
    <% @organization.projects.each do |project| %>
      <tr>
        <td class='main'><%= link_to project.title, project_path(project) %></td>
        <td><%= render partial: 'connectable/statuses', locals: { resourse: project } %></td>
        <td><%= link_to 'Редактировать', edit_project_path(project) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Обновить', get_from_azure_organization_projects_path(@organization), class: 'btn primary' %>